default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: SDM1_development

test: &test
  <<: *default
  database: SDM1_test

production:
  <<: *default
  database: SDM_production
  
cucumber:
  <<: *test
